### PR TITLE
This commit adds Reactor Pipes.

### PR DESCRIPTION
**Pull request by ifesdjeen**
This commit adds Reactor Pipes, a performant way to build complex processing topologies, including elements such as Pipe, MatchedPipe, AnonymousPipe, Channel: primitives for building performant reactive applications.

Code was extracted from [Halflife](https://github.com/ifesdjeen/halflife), naming convention was adjusted to avoid collisions with other Reactor projects.

Pitfalls: currently Pipes only works with java8. It will be eventually backported to java7.

Pros: Pipes helps to build topologies that are ready for distributed processing: pluggable persistency for topology components, per-entity pipes, very fast ( `O(1)` ) lookup for every dispatched message.

### CODE REVIEW

**Comment by smaldini** [comment]
awesomeness!

**Comment by smaldini** [comment]
let me know if you want to wait before we evaluate the PR to merge or you want to start immediately and merge this one as a base and do subsequents PR to improve later.

**Comment by ifesdjeen** [comment]
@smaldini this is just a beginning. I'd merge it and continue, this way we could start publish a 0.0.1 and start collecting feedback (that was also why i've started with docs early, too). I'm sure it'll be another couple of months until there's a GA.

**Comment by ifesdjeen** [comment]
<3 by the power given me by @smaldini, I hereby merge this initial Pull request for further evaluation!

**Comment by ifesdjeen** [comment]
I'll adjust / improve the documentation and readme tonight and we can announce a little addition @smaldini :)

**Pull request merged**
